version: '2.3'
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.4.0.0/16
  redis-network:
    driver: bridge

volumes:
  pgdata:
  redis:
  redis-config:

services:
  redis:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 8081:8081
    networks:
      - postgres
    depends_on:
      - redis